name: Build and Deploy to Pages

on:
  push:
    branches: ['master']

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v1
        id: pages
      - uses: actions/setup-node@v3
        name: Install Node
        with:
          node-version: 20.10.0
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.14.0
          run_install: false
      - run: pnpm install
      - run: pnpm build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
